"""empty message

Revision ID: 12aa09166b64
Revises: 1abcac767d47
Create Date: 2024-06-04 09:01:43.814304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = '12aa09166b64'
down_revision: Union[str, None] = '1abcac767d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_private_tags_tag_id_fkey', 'book_private_tags', type_='foreignkey')
    op.create_foreign_key(None, 'book_private_tags', 'tags', ['tag_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(None, 'books_private', ['slug'])
    op.alter_column('general_books', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('general_books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('general_books_tags_tag_id_fkey', 'general_books_tags', type_='foreignkey')
    op.drop_constraint('general_books_tags_general_book_id_fkey', 'general_books_tags', type_='foreignkey')
    op.create_foreign_key(None, 'general_books_tags', 'tags', ['tag_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'general_books_tags', 'general_books', ['general_book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'general_books_tags', type_='foreignkey')
    op.drop_constraint(None, 'general_books_tags', type_='foreignkey')
    op.create_foreign_key('general_books_tags_general_book_id_fkey', 'general_books_tags', 'general_books', ['general_book_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('general_books_tags_tag_id_fkey', 'general_books_tags', 'tags', ['tag_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('general_books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('general_books', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_constraint(None, 'books_private', type_='unique')
    op.drop_constraint(None, 'book_private_tags', type_='foreignkey')
    op.create_foreign_key('book_private_tags_tag_id_fkey', 'book_private_tags', 'tags', ['tag_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###
