"""empty message

Revision ID: 14f676fc89ad
Revises: 689418973822
Create Date: 2024-05-22 09:53:14.594713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = '14f676fc89ad'
down_revision: Union[str, None] = '689418973822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_private', sa.Column('author', sa.VARCHAR(), nullable=False))
    op.drop_column('books_private', 'body')
    op.add_column('general_books', sa.Column('author', sa.VARCHAR(), nullable=True))
    op.drop_column('general_books', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_books', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('general_books', 'author')
    op.add_column('books_private', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('books_private', 'author')
    # ### end Alembic commands ###
