"""empty message

Revision ID: 4b0d7b29f6f3
Revises: 0924e9ffd78f
Create Date: 2024-06-04 14:58:51.790494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = '4b0d7b29f6f3'
down_revision: Union[str, None] = '0924e9ffd78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_private', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint('books_private_user_email_fkey', 'books_private', type_='foreignkey')
    op.create_foreign_key(None, 'books_private', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('books_private', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_private', sa.Column('user_email', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books_private', type_='foreignkey')
    op.create_foreign_key('books_private_user_email_fkey', 'books_private', 'users', ['user_email'], ['email'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('books_private', 'user_id')
    # ### end Alembic commands ###
