"""empty message

Revision ID: 74615edcf57c
Revises: 5f6baac1d275
Create Date: 2024-05-14 14:19:05.843813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = '74615edcf57c'
down_revision: Union[str, None] = '5f6baac1d275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now', nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('picture', src.database.types.FileType(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('general_books_tags',
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('general_book_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['general_book_id'], ['general_books.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tag_id', 'general_book_id')
    )
    op.add_column('article_tags', sa.Column('article_id', sa.INTEGER(), nullable=False))
    op.drop_constraint('article_tags_general_book_id_fkey', 'article_tags', type_='foreignkey')
    op.create_foreign_key(None, 'article_tags', 'general_books', ['article_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('article_tags', 'general_book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_tags', sa.Column('general_book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.create_foreign_key('article_tags_general_book_id_fkey', 'article_tags', 'general_books', ['general_book_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('article_tags', 'article_id')
    op.drop_table('general_books_tags')
    op.drop_table('articles')
    # ### end Alembic commands ###
