"""empty message

Revision ID: 7947495f75db
Revises: 1df69d92d272
Create Date: 2024-05-19 21:33:53.678259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = '7947495f75db'
down_revision: Union[str, None] = '1df69d92d272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_constraint('categories_slug_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_slug_key', 'categories', ['slug'])
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
