"""empty message

Revision ID: 81b490574875
Revises: 2d524970f437
Create Date: 2024-05-28 21:46:56.075781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = '81b490574875'
down_revision: Union[str, None] = '2d524970f437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_private', sa.Column('picture', src.database.types.FileType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_private', 'picture')
    # ### end Alembic commands ###
