"""empty message

Revision ID: 8a39d572142d
Revises: 12aa09166b64
Create Date: 2024-06-04 09:31:04.458702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = '8a39d572142d'
down_revision: Union[str, None] = '12aa09166b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_private', 'general_book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_private', 'general_book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
