"""empty message

Revision ID: cb2e4aac0d18
Revises: 14f676fc89ad
Create Date: 2024-05-27 14:51:28.510835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = 'cb2e4aac0d18'
down_revision: Union[str, None] = '14f676fc89ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_private', sa.Column('general_book_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'books_private', 'general_books', ['general_book_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('general_books', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('general_books', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint(None, 'books_private', type_='foreignkey')
    op.drop_column('books_private', 'general_book_id')
    # ### end Alembic commands ###
