"""empty message

Revision ID: df6aa891d00d
Revises: 81b490574875
Create Date: 2024-06-01 11:18:08.179108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = 'df6aa891d00d'
down_revision: Union[str, None] = '81b490574875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_private', sa.Column('user_email', sa.VARCHAR(length=128), nullable=True))
    op.create_foreign_key(None, 'books_private', 'users', ['user_email'], ['email'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_private', type_='foreignkey')
    op.drop_column('books_private', 'user_email')
    # ### end Alembic commands ###
